---
include:
 # - board: xsplit_left
#    shield: nice_view
  - board: xsplit_right
    shield: nice_view_custom
  - board: xsplit_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: xsplit_studio_left
  - board: xsplit_left
    shield: settings_reset
