name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo (your repo)
        uses: actions/checkout@v3

      - name: Install west and deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev libffi-dev git
          pip3 install --user west
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install pyelftools
        run: pip3 install --user pyelftools

      - name: Clone ZMK firmware
        run: |
          git clone https://github.com/zmkfirmware/zmk.git zmk
          cd zmk
          west init -l app
          west update
          west zephyr-export
          
      - name: Install Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          tar xf zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          mv zephyr-sdk-0.16.4 ~/zephyr-sdk
          ~/zephyr-sdk/setup.sh -t all -c

      - name: Set Zephyr SDK environment
        run: |
          echo "ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV

      - name: Build Left
        run: |
          cd zmk
          west build -s app -b xsplit_left -- -DZMK_CONFIG="${{ github.workspace }}"

      - name: Build Right
        run: |
          cd zmk
          west build -s app -b xsplit_right -- -DZMK_CONFIG="${{ github.workspace }}"
